-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 17:01:57 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sscultivo
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sscultivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sscultivo` DEFAULT CHARACTER SET utf8 ;
USE `sscultivo` ;

-- -----------------------------------------------------
-- Table `sscultivo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `CC` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `email` VARCHAR(70) NOT NULL,
  `contraseña` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sscultivo`.`cultivos_tierra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`cultivos_tierra` (
  `idcultivo_tierra` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `planta` VARCHAR(45) NOT NULL,
  `cantidad_planta` INT NOT NULL,
  PRIMARY KEY (`idcultivo_tierra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sscultivo`.`cultivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`cultivos` (
  `id_cultivos` INT NOT NULL AUTO_INCREMENT,
  `tipo_cultivo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `pez` VARCHAR(45) NULL,
  `cantidad_pez` INT NULL,
  `planta` VARCHAR(45) NOT NULL,
  `cantidad_planta` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id_cultivos`),
  INDEX `fk_cultivo_acuaponico_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_cultivo_acuaponico_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sscultivo`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sscultivo`.`insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`insumos` (
  `id_insumos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  `precio_total` DOUBLE NOT NULL,
  `cultivos_id` INT NOT NULL,
  PRIMARY KEY (`id_insumos`),
  INDEX `fk_insumos_cultivo_acuaponico1_idx` (`cultivos_id` ASC),
  CONSTRAINT `fk_insumos_cultivo_acuaponico1`
    FOREIGN KEY (`cultivos_id`)
    REFERENCES `sscultivo`.`cultivos` (`id_cultivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sscultivo`.`insumos_has_cultivo_acuaponico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`insumos_has_cultivo_acuaponico` (
  `insumos_idinsumos` INT NOT NULL,
  `cultivo_acuaponico_idcultivo_acuaponico` INT NOT NULL,
  `cultivo_acuaponico_usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`insumos_idinsumos`, `cultivo_acuaponico_idcultivo_acuaponico`, `cultivo_acuaponico_usuario_id_usuario`),
  INDEX `fk_insumos_has_cultivo_acuaponico_cultivo_acuaponico1_idx` (`cultivo_acuaponico_idcultivo_acuaponico` ASC, `cultivo_acuaponico_usuario_id_usuario` ASC),
  INDEX `fk_insumos_has_cultivo_acuaponico_insumos1_idx` (`insumos_idinsumos` ASC),
  CONSTRAINT `fk_insumos_has_cultivo_acuaponico_insumos1`
    FOREIGN KEY (`insumos_idinsumos`)
    REFERENCES `sscultivo`.`insumos` (`id_insumos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_insumos_has_cultivo_acuaponico_cultivo_acuaponico1`
    FOREIGN KEY (`cultivo_acuaponico_idcultivo_acuaponico`)
    REFERENCES `sscultivo`.`cultivos` (`id_cultivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sscultivo`.`monitoreo_AC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`monitoreo_AC` (
  `idmonitoreo_AC` INT NOT NULL AUTO_INCREMENT,
  `fecha_AC` DATE NOT NULL,
  `temperatura` VARCHAR(45) NOT NULL,
  `nitrogeno` VARCHAR(45) NOT NULL,
  `nitritos` VARCHAR(45) NOT NULL,
  `oxigeno_disuelto` VARCHAR(45) NOT NULL,
  `proteina_alimento` VARCHAR(45) NOT NULL,
  `ph` VARCHAR(45) NOT NULL,
  `tiempo_crecimiento` VARCHAR(45) NOT NULL,
  `exposicion_solar` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `cultivos_id2` INT NOT NULL,
  PRIMARY KEY (`idmonitoreo_AC`),
  INDEX `fk_monitoreo_AC_cultivo_acuaponico1_idx` (`cultivos_id2` ASC),
  CONSTRAINT `fk_monitoreo_AC_cultivo_acuaponico1`
    FOREIGN KEY (`cultivos_id2`)
    REFERENCES `sscultivo`.`cultivos` (`id_cultivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sscultivo`.`monitoreo_TR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sscultivo`.`monitoreo_TR` (
  `idmonitoreo_TR` INT NOT NULL AUTO_INCREMENT,
  `fecha_TR` DATE NOT NULL,
  `ph` VARCHAR(45) NOT NULL,
  `humedad` INT NOT NULL,
  `nitrogeno` VARCHAR(45) NOT NULL,
  `fosforo` VARCHAR(45) NOT NULL,
  `potasio` VARCHAR(45) NOT NULL,
  `dioxidoCB` VARCHAR(45) NOT NULL,
  `comentario` VARCHAR(45) NOT NULL,
  `cultivos_id1` INT NOT NULL,
  PRIMARY KEY (`idmonitoreo_TR`),
  INDEX `fk_monitoreo_TR_cultivos1_idx` (`cultivos_id1` ASC),
  CONSTRAINT `fk_monitoreo_TR_cultivos1`
    FOREIGN KEY (`cultivos_id1`)
    REFERENCES `sscultivo`.`cultivos` (`id_cultivos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
